/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2021-01-12 09:22:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.EasyUI.datagrid.emp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class empManagerTypeH_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>사원관리(empManagerHType.html)</title>\r\n");
      out.write("<!-- 공통코드 추가 시작 \r\n");
      out.write("나중에는 이것들을 include를 사용해서 한 줄 추가로 하면 좋을거 같아요.\r\n");
      out.write("-->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"https://www.jeasyui.com/easyui/themes/default/easyui.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"https://www.jeasyui.com/easyui/themes/icon.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"https://www.jeasyui.com/easyui/themes/color.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"https://www.jeasyui.com/easyui/demo/demo.css\">\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://www.jeasyui.com/easyui/jquery.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://www.jeasyui.com/easyui/jquery.easyui.min.js\"></script>\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("       #d_msg {\r\n");
      out.write("          border: 5px solid gold;\r\n");
      out.write("          width: 700px;\r\n");
      out.write("          height: 120px;\r\n");
      out.write("       }\r\n");
      out.write("    </style>\r\n");
      out.write("<!-- 공통코드 추가   끝  -->\r\n");
      out.write("   <script type=\"text/javascript\">\r\n");
      out.write("      var v_date;//사용자가 선택한 날짜 정보를 담을 변수 선언.\r\n");
      out.write("      var editIndex = undefined;\r\n");
      out.write("      var g_empno=0;//여기에 사원번호를 담기 - 만일 0이면 선택을 안한경우이다.\r\n");
      out.write("      var g_cnt=0;//사용자가 선택한 row의 갯수 담기 - 1.선택은 개발자가 아니라 업무 담당자가 한다. - 2.컬럼을 선택할 것인가? 아니면 로우를 선택할 것인가?\r\n");
      out.write("    \t\t  \t  //3.한번 클릭으로 정할 것인가 아니면 더블클릭으로 정할 것인가?\r\n");
      out.write("       /* param1:사용자가 searchbox에 입력한 값 \r\n");
      out.write("       \t  param2:searchbox에 등록한 name값 -jsp나 서블릿에서 사용자가 입력한 값을 요청할때 사용한다.\r\n");
      out.write("       \t  ==>request.getParameter(\"sb_keyword\")\r\n");
      out.write("       */\r\n");
      out.write("       ////////////////////////////////// [[데이터 그리드에서 입력|수정|삭제 시작]] //////////////////////////////////////////////\r\n");
      out.write("       \r\n");
      out.write("       function empUpdate(){\r\n");
      out.write("       \t\tif(g_cnt == 0||g_empno==0){\r\n");
      out.write("       \t\t\t$.messager.alert('INFO','수정할 사원을 선택하세요');\r\n");
      out.write("       \t\t\treturn;\r\n");
      out.write("       \t\t}else{\r\n");
      out.write("       \t\t\t//before-오라클서버에 언제 갔다와야하는가? - 창이 열리기전에 갔다오는게 좋다 왜냐하면 화면이 열리기 전에 값이 결정되기 때문에\r\n");
      out.write("       \t\t\t//어떤 테이블에 갔다와야하는가? emp => 서버에서 처리됨 - select -> 1건\r\n");
      out.write("       \t\t\t$.ajax({\r\n");
      out.write("       \t\t\t\turl:'../../getEmpList3.jsp?g_empno='+g_empno //xxx.jsp?empno=7566[사용자가 선택한 row에서 가져와야한다.]\r\n");
      out.write("       \t\t\t\t,datatype:'json'//or html or xml\r\n");
      out.write("       \t\t\t\t,success:function(data){\r\n");
      out.write("       \t\t\t\t\t$(\"#b_msg\").append(data);//json포맷형식이 출력\r\n");
      out.write("       \t\t\t\t\tvar result = JSON.stringify(data);\r\n");
      out.write("       \t\t\t\t\talert(\"result: \"+result);//////////////////////////alert - result\r\n");
      out.write("       \t\t\t\t\tvar arr = JSON.parse(result);\r\n");
      out.write("       \t\t\t\t\tfor(var i=0;i<arr.length;i++){\r\n");
      out.write("       \t\t\t\t\t\t$('#u_empno').numberbox('setValue',arr[i].EMPNO);//초기화되는 부분 - UI\r\n");
      out.write("       \t\t\t\t\t\t\r\n");
      out.write("       \t\t\t\t\t}\r\n");
      out.write("       \t\t\t\t}\r\n");
      out.write("       \t\t\t});\r\n");
      out.write("       \t\t\t\r\n");
      out.write("       \t\t  $('#dlg_upd').dialog('open');//브라우저\r\n");
      out.write("       \t\t}\r\n");
      out.write("//        \t\t$('#dg_emp').treegrid('update',{\r\n");
      out.write("//        \t\t\tid: 2,\r\n");
      out.write("//        \t\t\trow: {\r\n");
      out.write("//        \t\t\t\tname: 'new name',\r\n");
      out.write("//        \t\t\t\ticonCls: 'icon-save'\r\n");
      out.write("//        \t\t\t}\r\n");
      out.write("//        \t\t});\t\r\n");
      out.write("       \t  }\r\n");
      out.write("       \t  function updAction(){////////////////////////////사원정보를 수정했을때 테이블에 올리기\r\n");
      out.write("       \t\t  \r\n");
      out.write("       \t\t  \r\n");
      out.write("       \t  }\r\n");
      out.write("       \t  function zipcode_ins(){//////////////////////////zipcode 정보 사원테이블에 넣기\r\n");
      out.write("       \t\t  \r\n");
      out.write("       \t  }\r\n");
      out.write("       function insert(){\r\n");
      out.write("       \t\tvar row = $('#dg_emp').datagrid('getSelected');//선택한 로우의 번호를 가져옴 - table\r\n");
      out.write("//        \t\t$(\"#d_msg\").append('row:'+row+'<br>');\r\n");
      out.write("\t\t\tif (row){//boolen 0:false , 값이 들어있으면:ture\r\n");
      out.write("\t\t\t\tvar index = $('#dg_emp').datagrid('getRowIndex', row);\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tindex = 0;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$('#dg_emp').datagrid('insertRow', {\r\n");
      out.write("\t\t\t\tindex: index\r\n");
      out.write("\t\t\t\t//넥사크로의 DataSet header꾸미기\r\n");
      out.write("\t\t\t\t,row:{\r\n");
      out.write("\t\t\t\t\tCK:0\r\n");
      out.write("\t\t\t\t\t,EMPNO:0\r\n");
      out.write("\t\t\t\t\t,ENAME:''\r\n");
      out.write("\t\t\t\t\t,JOB:''\r\n");
      out.write("\t\t\t\t\t,MGR:0\r\n");
      out.write("\t\t\t\t\t,SAL:'0.0'\r\n");
      out.write("\t\t\t\t\t,COMM:'0.0'\r\n");
      out.write("\t\t\t\t\t,DEPTNO:''\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("//        \t\t$(\"#d_msg\").append('index:'+index);\r\n");
      out.write("\t\t\t$('#dg_emp').datagrid('selectRow',index);\r\n");
      out.write("\t\t\t$('#dg_emp').datagrid('beginEdit',index);\r\n");
      out.write("       \t  }\r\n");
      out.write("       function getRowIndex(target){\r\n");
      out.write("//        \t\t$(\"#d_msg\").append('target:'+target);\r\n");
      out.write("    \t    var tr = $(target).closest('tr.datagrid-row');\r\n");
      out.write("    \t    return parseInt(tr.attr('datagrid-row-index'));\r\n");
      out.write("    \t}\r\n");
      out.write("    \tfunction editrow(target){\r\n");
      out.write("    \t    $('#dg_emp').datagrid('beginEdit', getRowIndex(target));\r\n");
      out.write("\t\t\r\n");
      out.write("    \t}\r\n");
      out.write("    \tfunction deleterow(target){\r\n");
      out.write("    \t    $.messager.confirm('Confirm','Are you sure?',function(r){\r\n");
      out.write("    \t        if (r){\r\n");
      out.write("    \t        }\r\n");
      out.write("    \t    });\r\n");
      out.write("    \t}\r\n");
      out.write("    \tfunction saverow(target){\r\n");
      out.write("    \t    $('#dg_emp').datagrid('endEdit', getRowIndex(target));\r\n");
      out.write("    \t}\r\n");
      out.write("    \tfunction cancelrow(target){\r\n");
      out.write("    \t    $('#dg_emp').datagrid('cancelEdit', getRowIndex(target));\r\n");
      out.write("    \t}\r\n");
      out.write("       ////////////////////////////////// [[데이터 그리드에서 입력|수정|삭제 끝]] //////////////////////////////////////////////\r\n");
      out.write("       //////////============================= [[우편번호 가져오기 시작]] ======================================/////////\r\n");
      out.write("       function zipCode(){\r\n");
      out.write("       \t\t  $('#dlg_zipcode').dialog('open');\r\n");
      out.write("       \t\t  \t\t\r\n");
      out.write("       }\r\n");
      out.write("  \r\n");
      out.write("       function zipcode_search(){\r\n");
      out.write("    \t   var dong = $(\"#dong\").val();\r\n");
      out.write("    \t   var zdo = $(\"#zdo\").val();\r\n");
      out.write("    \t   if(zdo == null || zdo.length<1){\r\n");
      out.write("    \t\t   $.messager.alert('INFO','지역를 선택해주세요.');\r\n");
      out.write("    \t   }\r\n");
      out.write("    \t   if(addr == null || addr.length<1 ){\r\n");
      out.write("    \t\t   $.messager.alert('INFO','주소를 입력해주세요.');\r\n");
      out.write("      \t\t\treturn;   \r\n");
      out.write("    \t   } else {\r\n");
      out.write("\t\t    \t$(\"#dg_zipcode\").datagrid({\r\n");
      out.write("\t\t    \t\turl:'../../getZipCodeList.jsp?dong='+addr+'&zdo='+zdo/* 전체조회와 조건검색 조회를 하나의 메소드로 할 것인지, 아니면 다른 메소드로 할것인지 결정해야 한다. */\r\n");
      out.write("// \t\t    \t\turl:'../../getZipCodeList.jsp?dong='+$(\"#dong\").val()+'&zdo='+$('#zdo').val()/* 전체조회와 조건검색 조회를 하나의 메소드로 할 것인지, 아니면 다른 메소드로 할것인지 결정해야 한다. */\r\n");
      out.write("\t\t    \t\t,method:'post'\r\n");
      out.write("\t\t    \t\t,onloadSuccess:function(data){\r\n");
      out.write("\t\t    \t\t\tvar result = JSON.stringify(data);\r\n");
      out.write("\t\t    \t\t\talert(result);\r\n");
      out.write("\t\t    \t\t\tvar jsonDoc = JSON.parse(result);\r\n");
      out.write("\t\t\t\t\t\tfor(var i=0;i<jsonDoc.length;i++)\r\n");
      out.write("\t\t\t\t\t\t\t$('#dg_zipcode').datagrid('setValue',arr[i].ADDRESS);\r\n");
      out.write("    \t\t   \t\t\t}\r\n");
      out.write("\t    \t\t});\r\n");
      out.write("    \t   }\r\n");
      out.write("       }\r\n");
      out.write("       //////////////======================================== [[우편번호 가져오기 끝]] =================================/////////////\r\n");
      out.write("      var cols;\r\n");
      out.write("//        function empSearch(){\r\n");
      out.write("// \t        //화면에 갱신처리 하기\r\n");
      out.write("// \t        //페이지를 이동해야 하는가? -이동해야하는 경우, 이동하지 않아도 되는경우?\r\n");
      out.write("// \t        //아니면 현재 보고 있는 페이지에서 처리 가능한가? -갱신처리 가능\r\n");
      out.write("// \t        //datagrid를 활용함. -url을 통해서 jsp 혹은 서블릿을 경유(갔다가 다시 온다)할수 있다.\r\n");
      out.write("// \t    \t$(\"#dg_emp\").datagrid({\r\n");
      out.write("// \t    \t\turl:'../../getEmpList3.jsp?cols='+$(\"#cb_gubun\").val()+\"&keyword=\"+$(\"#sb_keyword\").val()/* 전체조회와 조건검색 조회를 하나의 메소드로 할 것인지, 아니면 다른 메소드로 할것인지 결정해야 한다. */\r\n");
      out.write("// \t    \t\t,method:'post'\r\n");
      out.write("// \t    \t\t,onloadSuccess:function(data){\r\n");
      out.write("// \t    \t\t\tvar result = JSON.stringify(data);\r\n");
      out.write("// // \t    \t\t\tvar jsonDoc = JSON.parse(result);\r\n");
      out.write("// // \t    \t\t\talert(result);\r\n");
      out.write("// // \t\t\t\t\tfor(var i=0;i<jsonDoc.length;i++)\r\n");
      out.write("// // \t    \t\t\t\talert(\"empno:\"+jsonDoc[i].EMPNO);\r\n");
      out.write("// \t    \t\t}\r\n");
      out.write("// \t    \t});\r\n");
      out.write("//        }\r\n");
      out.write("//        function empSearch2(){\r\n");
      out.write("// \t    \t$(\"#dg_emp\").datagrid({\r\n");
      out.write("// \t    \t\turl:'../../getEmpList3.jsp?cols='+$(\"#cb_gubun\").val()+\"&keyword=\"+$(\"#tb_keyword\").val()/* 전체조회와 조건검색 조회를 하나의 메소드로 할 것인지, 아니면 다른 메소드로 할것인지 결정해야 한다. */\r\n");
      out.write("// \t    \t\t,method:'post'\r\n");
      out.write("// \t    \t\t,onloadSuccess:function(data){\r\n");
      out.write("// \t    \t\t\tvar result = JSON.stringify(data);\r\n");
      out.write("// // \t    \t\t\talert(result);\r\n");
      out.write("// \t    \t\t}\r\n");
      out.write("// \t    \t});\r\n");
      out.write("//        }\r\n");
      out.write("       function empSearch3(){\r\n");
      out.write("    \t   var keyword;//사용자가 입력한 값 담기\r\n");
      out.write("    \t   if($('#sb_keyword').val().length>0){\r\n");
      out.write("    \t\t   keyword=$(\"#sb_keyword\").val();\r\n");
      out.write("    \t   }\r\n");
      out.write("    \t   if($('#tb_keyword').val().length>0){\r\n");
      out.write("    \t\t   keyword=$(\"#tb_keyword\").val();\r\n");
      out.write("    \t   }\r\n");
      out.write("    \t    $(\"#d_msg\").append(tb_keyword+\",\"+sb_keyword+\",\"+keyword+\"<br>\");\r\n");
      out.write("\t    \t$(\"#dg_emp\").datagrid({\r\n");
      out.write("// \t\t\t\tkeyword.val();\r\n");
      out.write("\t    \t\turl:'../../getEmpList3.jsp?cols='+$(\"#cb_gubun\").val()+\"&keyword=\"+keyword+\"&timestamp=\"+new Date().getTime()/*\"&timestamp=\"+new Date().getTime()을 쓴이유는 0.01초단위로 확인하기 위해*/\r\n");
      out.write("\t    \t\t,method:'post'\r\n");
      out.write("\t    \t\t,onloadSuccess:function(data){\r\n");
      out.write("\t    \t\t\tvar result = JSON.stringify(data);\r\n");
      out.write("\t    \t\t\t\r\n");
      out.write("\t    \t\t}\r\n");
      out.write("\t    \t});\r\n");
      out.write("       }\r\n");
      out.write("       function endEditing(){\r\n");
      out.write("           if (editIndex == undefined){return true}\r\n");
      out.write("           if ($('#dg_emp').datagrid('validateRow', editIndex)){\r\n");
      out.write("               $('#dg_emp').datagrid('endEdit', editIndex);\r\n");
      out.write("               editIndex = undefined;\r\n");
      out.write("               return true;\r\n");
      out.write("           } else {\r\n");
      out.write("               return false;\r\n");
      out.write("           }\r\n");
      out.write("       }\r\n");
      out.write("//        function onClickCell(index, field){\r\n");
      out.write("//            if (editIndex != index){\r\n");
      out.write("//                if (endEditing()){\r\n");
      out.write("//                    $('#dg_emp').datagrid('selectRow', index)\r\n");
      out.write("//                            .datagrid('beginEdit', index);\r\n");
      out.write("//                    var ed = $('#dg_emp').datagrid('getEditor', {index:index,field:field});\r\n");
      out.write("//                    if (ed){\r\n");
      out.write("//                        ($(ed.target).data('textbox') ? $(ed.target).textbox('textbox') : $(ed.target)).focus();\r\n");
      out.write("//                    }\r\n");
      out.write("//                    editIndex = index;\r\n");
      out.write("//                } else {\r\n");
      out.write("//                    setTimeout(function(){\r\n");
      out.write("//                        $('#dg_emp').datagrid('selectRow', editIndex);\r\n");
      out.write("//                    },0);\r\n");
      out.write("//                }\r\n");
      out.write("//            }\r\n");
      out.write("//        }\r\n");
      out.write("       function onEndEdit(index, row){\r\n");
      out.write("           var ed = $(this).datagrid('getEditor', {\r\n");
      out.write("               index: index,\r\n");
      out.write("               field: 'EMPNO'\r\n");
      out.write("           });\r\n");
      out.write("//            row.DEPTNO = $(ed.target).textrbox('getText');\r\n");
      out.write("       }\r\n");
      out.write("       function append(){\r\n");
      out.write("           if (endEditing()){\r\n");
      out.write("               $('#dg_emp').datagrid('appendRow',{status:'P'});\r\n");
      out.write("               editIndex = $('#dg_emp').datagrid('getRows').length-1;\r\n");
      out.write("               $('#dg_emp').datagrid('selectRow', editIndex)\r\n");
      out.write("                       .datagrid('beginEdit', editIndex);\r\n");
      out.write("           }\r\n");
      out.write("       }\r\n");
      out.write("       function removeit(){\r\n");
      out.write("           if (editIndex == undefined){return}\r\n");
      out.write("           $('#dg_emp').datagrid('cancelEdit', editIndex)\r\n");
      out.write("                   .datagrid('deleteRow', editIndex);\r\n");
      out.write("           editIndex = undefined;\r\n");
      out.write("       }\r\n");
      out.write("       function acceptit(){\r\n");
      out.write("           if (endEditing()){\r\n");
      out.write("               $('#dg_emp').datagrid('acceptChanges');\r\n");
      out.write("           }\r\n");
      out.write("       }\r\n");
      out.write("       function reject(){\r\n");
      out.write("           $('#dg_emp').datagrid('rejectChanges');\r\n");
      out.write("           editIndex = undefined;\r\n");
      out.write("       }\r\n");
      out.write("       function getChanges(){\r\n");
      out.write("           var rows = $('#dg_emp').datagrid('getChanges');\r\n");
      out.write("           alert(rows.length+' rows are changed!');\r\n");
      out.write("       }\r\n");
      out.write("  \r\n");
      out.write("      //너 조회할거야?\r\n");
      out.write("      function empList(){\r\n");
      out.write("         $(\"#d_msg\").append(\"empList호출 성공<br>\");\r\n");
      out.write("         $(\"#dg_emp\").datagrid({\r\n");
      out.write("//             url: \"../emp2.json\"/* 서버의 이전이나 소스의 재사용성을 고려하여 상대경로로 작성할것. */   \r\n");
      out.write("            url: \"../../getEmpList3.jsp\"/* 서버의 이전이나 소스의 재사용성을 고려하여 상대경로로 작성할것. */   \r\n");
      out.write("         });\r\n");
      out.write("      }                  \r\n");
      out.write("   </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<script type=\"text/javascript\">   \r\n");
      out.write("   $(document).ready(function (){\r\n");
      out.write("\t   $('#btn_search').linkbutton({\r\n");
      out.write("\t\t   onclick:function(){\r\n");
      out.write("\t\t\t   $('#dlg_zipcode').dialog({\r\n");
      out.write("\t\t\t\t   \r\n");
      out.write("\t\t\t\t   \r\n");
      out.write("\t\t\t   });\r\n");
      out.write("\t\t   }\r\n");
      out.write("\t   });\r\n");
      out.write("\t   $('#tb_keyword').textbox('textbox').bind('keydown', function(e){\r\n");
      out.write("\t\t   \tif (e.keyCode == 13){\t\r\n");
      out.write("\t\t\t\tempSearch3();\r\n");
      out.write("\t\t   \t}\r\n");
      out.write("\t   });\r\n");
      out.write("\t   $('#dong').textbox('textbox').bind('keydown', function(e){\r\n");
      out.write("\t   \t\tif (e.keyCode == 13){\t\r\n");
      out.write("\t   \t\t\tzipcode_search();\r\n");
      out.write("\t   \t\t}\r\n");
      out.write("\t   });\r\n");
      out.write("\t   \t$('#dg_zipcode').datagrid({\r\n");
      out.write("\t   \t\tsingleSelect:true\r\n");
      out.write("\t   \t\t,columns:[[\r\n");
      out.write("\t   \t\t\t{field:'ZIPCODE' ,title:'주소번호',width:100, align:'center'}\r\n");
      out.write("\t   \t\t\t,{field:'ADDRESS',title:'주소번지',width:597, align:'center', editor:'text'}\r\n");
      out.write("\t   \t\t]]\r\n");
      out.write("\t   \t});\r\n");
      out.write("\t\t$('#zdo').combobox({\r\n");
      out.write("\t\t    url:'../../getZdoList.jsp',\r\n");
      out.write("\t\t    valueField:'ZDO',\r\n");
      out.write("\t\t    textField:'ZDO'\r\n");
      out.write("\t\t});\r\n");
      out.write("\t   //콤보박스 초기화 및 설정하기\r\n");
      out.write("        $(\"#cb_gubun\").combobox({\r\n");
      out.write("\t   \t\tdata: [\r\n");
      out.write("\t   \t\t\t{cols:'empno', label:'사원번호'},\r\n");
      out.write("\t   \t\t\t{cols:'enamo', label:'사원이름'},\r\n");
      out.write("\t   \t\t\t{cols:'sal'\t , label:'급여'}\r\n");
      out.write("\t   \t\t]\r\n");
      out.write("         ,onSelect: function(rec){/*  콤보에서 선택 했을때 @param:object로 로우에 주소번지를 갖는다. row.empno ,row.ename */\r\n");
      out.write("//         \t \talert(\"선택한로우의 컬럼정보 :\"+rec.cols);\r\n");
      out.write("// \t            var url = '../../getEmpList.jsp?empno='+rec.cols;\r\n");
      out.write("//         \t \tcols = rec.cols; \t\r\n");
      out.write("\t        }\r\n");
      out.write("        });\r\n");
      out.write("\t   //데이터그리드 초기화 및 설정하기\r\n");
      out.write("         $(\"#dg_emp\").datagrid({\r\n");
      out.write("            toolbar:'#tbar_emp'\r\n");
      out.write("            ,singleSelect:true\r\n");
      out.write("\t\t\t,columns:[[\r\n");
      out.write("\t\t\t\t\t   {field:'CK'\t\t,checkbox:'true',width:50,  align:'center'}\r\n");
      out.write("\t\t\t\t\t   ,{field:'EMPNO'\t,title:'사원번호'\t,width:100, editor:'text'}\r\n");
      out.write("\t\t\t\t\t   ,{field:'ENAME'\t,title:'사원이름'\t,width:100, editor:'text'}\r\n");
      out.write("\t\t\t\t\t   ,{field:'JOB'  \t,title:'job'\t,width:130, editor:'text'}\r\n");
      out.write("\t\t\t\t\t   ,{field:'MGR'\t ,title:'그룹번호'\t,width:100, editor:'text'}\r\n");
      out.write("\t\t\t\t\t   ,{field:'HIREDATE',title:'입사일'\t,width:250, editor:'text', hidden:'true'}\r\n");
      out.write("\t\t\t\t\t   ,{field:'SAL'\t ,title:'급여'\t,width:100, editor:'text'}\r\n");
      out.write("\t\t\t\t\t   ,{field:'COMM'\t ,title:'인센티브'\t,width:100, editor:'text'}\r\n");
      out.write("\t\t\t\t\t   ,{field:'DEPTNO'\t ,title:'부서번호'\t,width:100,\teditor:'text',\r\n");
      out.write("\t\t\t\t\t\t   formatter:function(value, row){\r\n");
      out.write("\t\t\t\t\t\t\t   return row.deptno||value;\r\n");
      out.write("\t\t\t\t\t\t   }\r\n");
      out.write("\t\t\t\t\t\t   ,editor:{\r\n");
      out.write("\t\t\t\t\t\t\t type:'combobox'\r\n");
      out.write("\t\t\t\t\t\t\t ,options:{\r\n");
      out.write("\t\t\t\t\t\t\t\t valueField: 'DEPTNO'//실제 서버에 넘거가는 필드\r\n");
      out.write("\t\t\t\t\t\t\t\t ,textField: 'DNAME'\r\n");
      out.write("\t\t\t\t\t\t\t\t ,data:'DEPTNO'\r\n");
      out.write("\t\t\t\t\t\t\t\t ,url:'../dept.json'\r\n");
      out.write("\t\t\t\t\t\t\t }\r\n");
      out.write("\t\t\t\t\t\t   }\r\n");
      out.write("\t\t\t\t\t   }\r\n");
      out.write("\t\t\t\t\t   ,{field:'action',title:'Action',width:120,align:'center'\r\n");
      out.write("\t\t\t                ,formatter:function(value,row,index){\r\n");
      out.write("\t\t\t                    if (row.editing){\r\n");
      out.write("\t\t\t                        var s = '<a href=\"javascript:void(0)\" onclick=\"saverow(this)\">Save</a> ';\r\n");
      out.write("\t\t\t                        var c = '<a href=\"javascript:void(0)\" onclick=\"cancelrow(this)\">Cancel</a>';\r\n");
      out.write("\t\t\t                        return s+c;\r\n");
      out.write("\t\t\t                    }\r\n");
      out.write("// \t\t\t                    else {\r\n");
      out.write("// \t\t\t                        var e = '<a href=\"javascript:void(0)\" onclick=\"editrow(this)\">Edit</a> ';\r\n");
      out.write("// \t\t\t                        var d = '<a href=\"javascript:void(0)\" onclick=\"deleterow(this)\">Delete</a>';\r\n");
      out.write("// \t\t\t                        return e+d;\r\n");
      out.write("// \t\t\t                    }\r\n");
      out.write("\t\t\t                }\r\n");
      out.write("\t\t\t            }\r\n");
      out.write("\t\t\t]]\r\n");
      out.write("//          \t,onClickSel: onClickSel\r\n");
      out.write("//          \t,onEndEdit: onEndEdit\r\n");
      out.write("////////////////////////////////////////// [[데이터 그리드관련 이벤트핸들러 이름 시작]] ///////////////////////////////////////////////////////////         \t\r\n");
      out.write("//          \t,onEndEdit:function(index,row){\r\n");
      out.write("//                 var ed = $(this).datagrid('getEditor', {\r\n");
      out.write("//                     index: index,\r\n");
      out.write("//                     field: 'productid'\r\n");
      out.write("//                 });\r\n");
      out.write("//                 row.productname = $(ed.target).combobox('getText');\r\n");
      out.write("//             }\r\n");
      out.write("            ,onBeforeEdit:function(index,row){\r\n");
      out.write("            \talert(index);\r\n");
      out.write("                row.editing = true;\r\n");
      out.write("                $(this).datagrid('refreshRow', index);\r\n");
      out.write("            }\r\n");
      out.write("            ,onAfterEdit:function(index,row){\r\n");
      out.write("                row.editing = false;\r\n");
      out.write("                $(this).datagrid('refreshRow', index);\r\n");
      out.write("            }\r\n");
      out.write("            ,onCancelEdit:function(index,row){\r\n");
      out.write("                row.editing = false;\r\n");
      out.write("                $(this).datagrid('refreshRow', index);\r\n");
      out.write("            }\r\n");
      out.write("            ,onClickRow: function(index, row){\r\n");
      out.write("            \tg_empno = row.EMPNO; //여기서 사용자가 입력한 값이 된다.\r\n");
      out.write("            \tg_cnt = 1;\r\n");
      out.write("            }\r\n");
      out.write("            ,onDblClickRow: function(index, row){\r\n");
      out.write("            \t$('#dlg_upd').dialog('open');\r\n");
      out.write("        \t\t$('#u_empno').numberbox(\"setValue\",row.EMPNO);\r\n");
      out.write("        \t\t$('#u_ename').textbox(\"setValue\",row.ENAME);\r\n");
      out.write("        \t\t$('#u_job').textbox(\"setValue\",row.JOB);\r\n");
      out.write("        \t\t$('#u_hiredate').textbox(\"setValue\",row.HIREDATE);\r\n");
      out.write("        \t\t$('#u_sal').numberbox(\"setValue\",row.SAL);\r\n");
      out.write("        \t\t$('#u_comm').numberbox(\"setValue\",row.COMM);\r\n");
      out.write("        \t\t$('#u_deptno').combobox(\"setValue\",row.DEPTNO);\r\n");
      out.write("        \t\t$('#zipcode').textbox(\"setValue\",row.ZIPCODE);\r\n");
      out.write("        \t\t$('#mem_addr').textbox(\"setValue\",row.ADDRESS);\r\n");
      out.write("        \t}\r\n");
      out.write("            \r\n");
      out.write("////////////////////////////////////////// [[데이터 그리드관련 이벤트핸들러 이름 끝]] ///////////////////////////////////////////////////////////         \t\r\n");
      out.write("         });\r\n");
      out.write("   });\r\n");
      out.write("</script>\r\n");
      out.write("<!-- 이 페이지에 대한 에러 메시지나 힌트문을 출력하자. -->\r\n");
      out.write("<div id=\"d_msg\"></div>\r\n");
      out.write("<!-- ================================ [[ToolBar 추가하기 시작]] =================================================== -->\r\n");
      out.write("<div id=\"tbar_emp\">\r\n");
      out.write("\t\t<!-- 테이블 태그를 활용하여 조건 검색하는 화면을 추가하고 그 아래 버튼을 배치하시요. -->\r\n");
      out.write("\t\t<table border=\"0\" width=\"100%\">\r\n");
      out.write("\t\t\t<!-- 조건 검색 화면 시작 -->\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<table border=\"0\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"280px\">\r\n");
      out.write("\t\t\t\t\t\t\t<label width=\"100\">사원번호</label>\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"nb_empno\" class=\"easyui-numberbox\" style=\"width:200px;\" value=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"250px\">\r\n");
      out.write("\t\t\t\t\t\t\t<label width=\"100\">급여</label>\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"nb_sal\" class=\"easyui-numberbox\" value=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"300px\">\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"dd_hiredate\"\tclass=\"easyui-datebox\" label=\"날짜\" style=\"width:200px;\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("<!-- combobox추가 시작(위치선택, 공간 확보, 코드추가) 이름|job|부서번호 -->\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"1000px\" colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t\t\t<label width=\"100px\">검색분류</label>\r\n");
      out.write("<!-- =============================================== 이순신 2020.11.02 추가 시작 ========================================================== -->\r\n");
      out.write("\t\t\t\t\t<input id=\"cb_gubun\" class=\"easyui-combobox\" data-options=\"\r\n");
      out.write("\t\t\t       \t \tvalueField: 'cols',\r\n");
      out.write("\t\t\t        \ttextField: 'label'\">\r\n");
      out.write("<!-- =============================================== 이순신 2020.11.02 추가 시작 ========================================================== -->\r\n");
      out.write("\t\t\t\t\t<input id=\"sb_keyword\" name=\"sb_keyword\" class=\"easyui-searchbox\" data-options=\"searcher:empSearch3,prompt:'Please Input Value'\" style=\"width:300px\">\r\n");
      out.write("\t\t\t\t\t<input id=\"tb_keyword\" name=\"tb_keyword\" class=\"easyui-textbox\" onClick=\"empSearch3()\" data-options=\"prompt:'Please Input Value'\" style=\"width:300px\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("<!-- combobox추가 시작 -->\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr><!-- &nbsp = 띄어쓰기연산자 -->\r\n");
      out.write("\t\t\t<!-- 조건 검색화면 끝 -->\r\n");
      out.write("\t\t\t<!-- 업무관련 시작 -->\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" onclick=\"insert()\">Insert Row</a>\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" iconCls=\"icon-search\" plain=\"true\" onclick=\"empList()\">조회</a>\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" iconCls=\"icon-add\" \t plain=\"true\" onclick=\"addEmp()\">입력</a>\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" iconCls=\"icon-edit\" \t plain=\"true\" onclick=\"empUpdate()\">수정</a>\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" iconCls=\"icon-remove\" plain=\"true\" onclick=\"removeEmp()\">삭제</a>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<!-- 업무관련 끝 -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- ================================ [[ToolBar 추가하기 끝]] =================================================== -->\r\n");
      out.write("<div>\r\n");
      out.write("\t<div></div><table id=\"dg_emp\"  style=\"align:'center'\" class=\"esayui-datagrid\"  width=\"1200\" title=\"사원관리\"></table>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- ==========================================[[사원카드 등록 하기 시작]]======================================================================== -->\r\n");
      out.write("<!-- <div id=\"dlg_ins\" class=\"esayui-dialog\" style=\"width:600px; padding:30px 30px\" data-options=\"closed:true, title:'사원정보 입력'\"> -->\r\n");
      out.write("<!-- \t<form id=\"f_empins\"> -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("<!-- \t</form> -->\r\n");
      out.write("<!-- \t<div> -->\r\n");
      out.write("<!-- \t\t<a href=\"javascript:insAction()\" class=\"easyui-linkbutton\" iconCls=\"icon-save\">저장</a> -->\r\n");
      out.write("<!-- \t\t<a href=\"javascript:$('#dlg_ins').dialog('close')\" class=\"easyui-linkbutton\" iconCls=\"icon-cancel\" onclick=\"cancelEmp()\">닫기</a> -->\r\n");
      out.write("<!-- \t</div> -->\r\n");
      out.write("<!-- </div> -->\r\n");
      out.write("<!-- ==========================================[[사원카드 등록 하기 끝]]======================================================================== -->\r\n");
      out.write("<!-- ==========================================[[우편번호 검색 하기 시작]]======================================================================== -->\r\n");
      out.write("<div  id=\"dlg_zipcode\" name=\"dlg_zipcode\" style=\"width:800px; padding:30px 30px;\" class=\"easyui-dialog\" data-options=\"closed:'true', title:'주소찾기'\">\r\n");
      out.write("         <input id=\"zdo\" class=\"easyui-combobox\" name=\"zdo\" data-options=\"prompt:'지역'\" style=\"width:100px\">\r\n");
      out.write("         <input class=\"easyui-textbox\" id=\"dong\" name=\"dong\"\r\n");
      out.write("         \tlabelPosition=\"top\" style=\"width:500px\" data-options=\"prompt:'동이나 면을 입력하세요'\">\r\n");
      out.write("\t\t\t<a href=\"javascript:zipcode_search()\" class=\"easyui-linkbutton\">찾기</a>\r\n");
      out.write("\t\t\t<div style=\"margin-bottom:10px;\"></div>\r\n");
      out.write("\t        <table id=\"dg_zipcode\" class=\"esayui-datagrid\" height=\"700\" width=\"700\" title=\"주소찾기\"></table>\r\n");
      out.write("\t\t\t<a href=\"javascript:zipcode_ins()\" class=\"easyui-linkbutton\">확인</a>\r\n");
      out.write("\t\t\t<a href=\"javascript:$('#dlg_zipcode').dialog('close')\" class=\"easyui-linkbutton\">취소</a>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- ==========================================[[우편번호 검색 하기 끝]]======================================================================== -->\r\n");
      out.write("<!-- ==========================================[[사원카드 수정 하기 시작]]======================================================================== -->\r\n");
      out.write("<div id=\"dlg_upd\" name=\"dlg_upd\" style=\"width:600px; padding:30px 30px;\" class=\"easyui-dialog\" data-options=\"closed:'true', title:'사원정보 수정', footer:'#d_upd'\">\r\n");
      out.write("   <form id=\"f_empupd\">\r\n");
      out.write("         <div style=\"margin-bottom:10px\">\r\n");
      out.write("         <input class=\"easyui-numberbox\" id=\"u_empno\" name=\"empno\" label=\"사원번호\" data-options=\"prompt:'Enter a EmpNO'\" style=\"width:150px\">\r\n");
      out.write("         </div>\r\n");
      out.write("         <div style=\"margin-bottom:10px\">\r\n");
      out.write("         <input class=\"easyui-textbox\" id=\"u_ename\" name=\"ename\" label=\"사원명\" data-options=\"prompt:'Enter a ENAME'\" style=\"width:250px\">\r\n");
      out.write("         </div>\r\n");
      out.write("         <div style=\"margin-bottom:10px\">\r\n");
      out.write("         <input class=\"easyui-textbox\" id=\"u_job\" name=\"job\" label=\"JOB\" data-options=\"prompt:'Enter a JOB'\" style=\"width:250px\">\r\n");
      out.write("         </div>\r\n");
      out.write("         <div style=\"margin-bottom:10px\">\r\n");
      out.write("         <input class=\"easyui-textbox\" id=\"u_hiredate\" name=\"hiredate\" label=\"입사일자\" data-options=\"prompt:'Enter a 입사일자'\" style=\"width:250px\">\r\n");
      out.write("         </div>\r\n");
      out.write("         <div style=\"margin-bottom:10px\">\r\n");
      out.write("         <input class=\"easyui-numberbox\" id=\"u_sal\" name=\"sal\" label=\"급여\" data-options=\"prompt:'Enter a 급여'\" style=\"width:250px\">\r\n");
      out.write("         </div>         \r\n");
      out.write("         <div style=\"margin-bottom:10px\">\r\n");
      out.write("         <input class=\"easyui-numberbox\" id=\"u_comm\" name=\"comm\" label=\"인센티브\"  data-options=\"prompt:'Enter a 인센티브'\" style=\"width:250px\">\r\n");
      out.write("         </div>         \r\n");
      out.write("         <div style=\"margin-bottom:10px\">\r\n");
      out.write("         <input class=\"easyui-combobox\" id=\"u_deptno\" name=\"deptno\" label=\"부서번호\" style=\"width:250px\"\r\n");
      out.write("          data-options=\"prompt:'Enter a 부서번호'\r\n");
      out.write("                      \t,valueField: 'DEPTNO'\r\n");
      out.write("                         ,textField: 'DNAME'\r\n");
      out.write("                         ,url: 'http://192.168.0.38:9000/EasyUI/getDeptList.jsp'\r\n");
      out.write("                         ,onSelect: function(rec){\r\n");
      out.write("                      }\" \r\n");
      out.write("         >\r\n");
      out.write("         </div>         \r\n");
      out.write("         <div style=\"margin-bottom:10px\">\r\n");
      out.write("         <input class=\"easyui-textbox\" id=\"zipcode\" name=\"zipcode\" label=\"우편번호\" style=\"width:160px\" data-options=\"prompt:'Enter a ZIPCODE'\r\n");
      out.write("         \t\t\t\t ,valueField: 'ZIPCODE'\r\n");
      out.write("                         ,textField: 'ZIPCODE'\r\n");
      out.write("                         ,url: 'http://192.168.0.38:9000/EasyUI/getZipCodeList.jsp'\r\n");
      out.write("                         ,onSelect: function(rec){\r\n");
      out.write("                      }\">\r\n");
      out.write("         <a id=\"btn_search\" href=\"javascript:zipCode()\" class=\"easyui-linkbutton\">우편번호찾기</a>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div style=\"margin-bottom:10px\">\r\n");
      out.write("         <input class=\"easyui-textbox\" id=\"mem_addr\" name=\"mem_addr\" label=\"주소\" style=\"width:420px\" data-options=\"prompt:'Enter a ADDRESS'\r\n");
      out.write("         \t\t\t\t ,valueField:'ADDRESS'\r\n");
      out.write("                         ,textField: 'ADDRESS'\r\n");
      out.write("                         ,url: 'http://192.168.0.38:9000/EasyUI/getZipCodeList.jsp'\r\n");
      out.write("                         ,onSelect: function(rec){\r\n");
      out.write("                      }\" >\r\n");
      out.write("         </div>\r\n");
      out.write("   </form>\r\n");
      out.write("   <div>\r\n");
      out.write("      <!-- a태그는 문단이동 혹은 링크 마지막 자바스크립트 함수 호출이 가능함.(특정한 지점으로 바로 이동가능)  이클립스 ctrl + l 앵커\r\n");
      out.write("      data-options=\"toolbar:#tbar_emp\", footer:'#d_upd'\r\n");
      out.write("      -->\r\n");
      out.write("       <a href=\"javascript:updAction()\" class=\"easyui-linkbutton\" iconCls=\"icon-save\" plain=\"true\">저장</a>\r\n");
      out.write("        <a href=\"javascript:$('#dlg_upd').dialog('close')\" class=\"easyui-linkbutton\" iconCls=\"icon-cancel\" plain=\"true\">닫기</a>\r\n");
      out.write("       \r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- ==========================================[[사원카드 수정 하기 끝]]======================================================================== -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
