/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2021-01-05 00:59:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class writeForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/common/easyUI_common.jsp", Long.valueOf(1608771953305L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>글쓰기화면[webapp]</title>\r\n");
      out.write("<!-- ìì¤ê° íëë¡ í©ì³ì§ëê¹ ì ì¸ë¬¸ì´ ë ë² ì¬ íììë¤. -->\r\n");
      out.write("\t<link rel=\"shortcut icon\" href=\"image/favicon.ico\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"https://www.jeasyui.com/easyui/themes/default/easyui.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"https://www.jeasyui.com/easyui/themes/icon.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"https://www.jeasyui.com/easyui/themes/color.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"https://www.jeasyui.com/easyui/demo/demo.css\">\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://www.jeasyui.com/easyui/jquery.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/js/commons.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://www.jeasyui.com/easyui/jquery.easyui.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js\"></script>");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction addAction(){\r\n");
      out.write("\t\t//$(\"#f_write\").attr(\"method\",\"post\");\r\n");
      out.write("\t\t//$(\"#f_write\").attr(\"action\",\"/board/boardInsert.sp\");\r\n");
      out.write("\t\t$(\"#f_write\").submit();\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction writeClose(){\r\n");
      out.write("\t\twindow.close();\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"dlg_boardAdd\" title=\"글쓰기\" class=\"easyui-panel\" \r\n");
      out.write("style=\"width:650px;height:450px;padding:10px\" data-options=\"footer:'#tbar_boardAdd'\">\t\r\n");
      out.write("\t<form id=\"f_write\" action=\"/board/boardInsert.sp\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"bm_no\" value=\"0\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"bm_group\" value=\"0\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"bm_pos\" value=\"0\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"bm_step\" value=\"0\">\r\n");
      out.write("\t<table>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=\"100px\">제목</td>\r\n");
      out.write("\t\t\t<td width=\"500px\">\r\n");
      out.write("\t\t\t\t<input class=\"easyui-textbox\" data-options=\"width:'350px'\" id=\"bm_title\" name=\"bm_title\" required>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\t\r\n");
      out.write("\t\t\t<td width=\"100px\">작성자</td>\r\n");
      out.write("\t\t\t<td width=\"500px\">\r\n");
      out.write("\t\t\t\t<input class=\"easyui-textbox\" data-options=\"width:'150px'\" id=\"bm_writer\" name=\"bm_writer\" required>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=\"100px\">이메일</td>\r\n");
      out.write("\t\t\t<td width=\"500px\">\r\n");
      out.write("\t\t\t\t<input class=\"easyui-textbox\" data-options=\"width:'250px'\" id=\"bm_email\" name=\"bm_email\">\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\t\t\t\r\n");
      out.write("\t\t\t<td width=\"100px\">내용</td>\r\n");
      out.write("\t\t\t<td width=\"500px\">\r\n");
      out.write("\t\t\t\t<input class=\"easyui-textbox\" id=\"bm_content\" name=\"bm_content\" data-options=\"multiline:'true',width:'400px',height:'90px'\" required>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\t\t\t\r\n");
      out.write("\t\t\t<td width=\"100px\">비번</td>\r\n");
      out.write("\t\t\t<td width=\"500px\">\r\n");
      out.write("\t\t\t\t<input class=\"easyui-textbox\" data-options=\"width:'100px'\" id=\"bm_pw\" name=\"bm_pw\" required>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\t\t\t\r\n");
      out.write("\t\t\t<td width=\"100px\">첨부파일</td>\r\n");
      out.write("\t\t\t<td width=\"500px\">\r\n");
      out.write("\t\t\t\t<input class=\"easyui-filebox\" data-options=\"width:'450px'\" id=\"bs_file\" name=\"bs_file\">\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\t\r\n");
      out.write("\t<!-- 입력 화면 버튼 추가 -->\r\n");
      out.write("\t<div id=\"tbar_boardAdd\" align=\"right\">\r\n");
      out.write("\t\t<a href=\"javascript:addAction()\" class=\"easyui-linkbutton\" iconCls=\"icon-save\">저장</a>\r\n");
      out.write("\t\t<a href=\"javascript:writeClose()\" \r\n");
      out.write("\t\t   class=\"easyui-linkbutton\" iconCls=\"icon-cancel\">닫기</a>\r\n");
      out.write("\t</div>\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
