/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2021-01-25 19:26:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.cookclass;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class cookingClassRegisterContent_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/navbar.jsp", Long.valueOf(1610644861660L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1609059653918L));
    _jspx_dependants.put("/loginOkHeader.jsp", Long.valueOf(1610894683264L));
    _jspx_dependants.put("/common/bootstrap_common.jsp", Long.valueOf(1611325921671L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1610535124457L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

 String id = (String)session.getAttribute("id"); 
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");

       StringBuilder path = new StringBuilder(request.getContextPath());
       path.append("/");
    
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\" integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"image/favicon.ico\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(path.toString() );
      out.write("css/team.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(path.toString() );
      out.write("css/bootstrap.min.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path.toString() );
      out.write("js/bootstrap.min.js\"></script> \r\n");
      out.write("\r\n");
      out.write("<!-- carousel -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  \r\n");
      out.write("<!-- font -->\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Black+Han+Sans&display=swap\" rel=\"stylesheet\"> \r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Nanum+Pen+Script&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Sunflower:wght@300&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Single+Day&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Jua&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("<!-- EasyUI -->\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"https://www.jeasyui.com/easyui/themes/material/easyui.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"https://www.jeasyui.com/easyui/themes/icon.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"https://www.jeasyui.com/easyui/themes/color.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(path.toString() );
      out.write("css/demo.css\">\r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.print(path.toString() );
      out.write("js/commons.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://www.jeasyui.com/easyui/jquery.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://www.jeasyui.com/easyui/jquery.easyui.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("<!-- Ajax -->\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- kakao Login API -->\r\n");
      out.write("<script src=\"https://developers.kakao.com/sdk/js/kakao.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("<!-- google chart -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://www.gstatic.com/charts/loader.js\"></script>\r\n");
      out.write("<title>오늘 뭐 먹지?</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path.toString() );
      out.write("js/cookclass.js\"></script>\r\n");
      out.write("<script src=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write(" \t/* =========================================== 다음 우편주소 검색 =========================================================== */\r\n");
      out.write(" \tfunction daumzip() {\r\n");
      out.write("        new daum.Postcode({\r\n");
      out.write("            oncomplete: function(data) {\r\n");
      out.write("                // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("\r\n");
      out.write("                // 도로명 주소의 노출 규칙에 따라 주소를 표시한다.\r\n");
      out.write("                // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("                var roadAddr = data.roadAddress; // 도로명 주소 변수\r\n");
      out.write("                var extraRoadAddr = ''; // 참고 항목 변수\r\n");
      out.write("\r\n");
      out.write("                // 법정동명이 있을 경우 추가한다. (법정리는 제외)\r\n");
      out.write("                // 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\r\n");
      out.write("                if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){\r\n");
      out.write("                    extraRoadAddr += data.bname;\r\n");
      out.write("                }\r\n");
      out.write("                // 건물명이 있고, 공동주택일 경우 추가한다.\r\n");
      out.write("                if(data.buildingName !== '' && data.apartment === 'Y'){\r\n");
      out.write("                   extraRoadAddr += (extraRoadAddr !== '' ? ', ' + data.buildingName : data.buildingName);\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                // 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("\t\t\t\tif(document.getElementById(\"c_zip\").value != null){\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"c_zip\").value = ''\r\n");
      out.write("\t\t\t\t} \r\n");
      out.write("\t\t\t\tdocument.getElementById(\"c_zip\").value = roadAddr;\r\n");
      out.write("                $.ajax({\r\n");
      out.write("            \t\turl:location.href\r\n");
      out.write("\t\t\t\t\t,success:function(data){\r\n");
      out.write("// \t\t\t\t\t\talert(\"m_addr:\"+roadAddr);\r\n");
      out.write("\t\t\t\t\t\t$(\"c_zip\").text(roadAddr);\r\n");
      out.write("                   }\r\n");
      out.write("            \t});\r\n");
      out.write("\t                \r\n");
      out.write("            }\r\n");
      out.write("        }).open();\r\n");
      out.write("    }\r\n");
      out.write(" \t\r\n");
      out.write(" \t/* =========================================== 다음 우편주소 검색 =========================================================== */\r\n");
      out.write(" \t\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<table align=\"center\" style=\"width: 70% ; height: 100%;\">\r\n");
      out.write("\t\t\t<!-- Header -->\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t");
if(session.getAttribute("nick")!=null){ 
      out.write("<td colspan=\"2\" style=\"width: 100%; padding-top: 2%; padding-bottom: 2%;\">\r\n");
      out.write("\t\t\t\t");
 String nick = (String)session.getAttribute("nick");
      out.write("<table style=\"width: 100%;\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td style=\"width: 30%; text-align: center;\">\r\n");
      out.write("\t\t\t\t<a href=\"/member/index.jsp\">\r\n");
      out.write("\t\t\t\t\t<input type=\"image\" src=\"/images/logo.jpg\"  style=\"width: 200px\">\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td style=\"width: 45%; text-align: center;\">\r\n");
      out.write("\t\t\t\t<form class=\"form-inline\" action=\"#\" method=\"get\">\r\n");
      out.write("\t\t\t\t<div class=\"easyui-panel\" style=\"width: 20%; max-width: 400px;\">\r\n");
      out.write("\t\t\t\t\t\t<select class=\"easyui-combobox\" name=\"state\"  style=\"width: 100%;\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"AL\">제목</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"AK\">내용</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"AZ\">재료명</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"AR\">닉네임</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"AR\">분류</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"AR\">소분류</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<input class=\"form-control mr-sm-2\" type=\"search\" placeholder=\"Search...\" aria-label=\"Search\" style=\"width: 55%\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-secondary\">\r\n");
      out.write("\t\t\t\t\t\t\t<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-search\" viewBox=\"0 0 16 16\">\r\n");
      out.write("\t\t\t\t\t\t\t  <path fill-rule=\"evenodd\"d=\"M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z\" />\r\n");
      out.write("\t\t\t\t\t\t\t  <path fill-rule=\"evenodd\"d=\"M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z\" />\r\n");
      out.write("\t\t\t\t\t\t\t</svg>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td style=\"width: 12%;  padding-top: 32px; text-align: right;\">\r\n");
      out.write("\t\t\t\t<p style=\"font-family: Black Han Sans, sans-serif; color: black;\">");
      out.print(nick);
      out.write("님 환영합니다</p>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td style=\"width: 8%;  padding-top: 15px; text-align: right\">\r\n");
      out.write("\t\t\t\t<a href=\"/member/mypage.jsp\" style=\"font-family: Black Han Sans, sans-serif; color: black;\">\r\n");
      out.write("\t\t\t\t\t마이페이지\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td style=\"width: 8%; padding-top: 15px; padding-left:5px; text-align: left; \">\r\n");
      out.write("\t\t\t\t<a href=\"javascript:logout();\"  style=\"font-family: Black Han Sans, sans-serif; color: black; cursor: pointer;\">\r\n");
      out.write("\t\t\t\t\t로그아웃\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</td>\r\n");
      out.write("\t\t\t");
}else{ 
      out.write("<td colspan=\"2\" style=\"width: 100%; padding-top: 2%; padding-bottom: 2%;\">\r\n");
      out.write("\t\t\t\t");
      out.write("<table style=\"width: 100%;\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td style=\"width: 30%; text-align: center;\">\r\n");
      out.write("\t\t\t\t<a href=\"/member/index.jsp\">\r\n");
      out.write("\t\t\t\t\t<input type=\"image\" src=\"/images/logo.jpg\"  style=\"width: 200px\">\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td style=\"width: 45%; text-align: center;\">\r\n");
      out.write("\t\t\t\t<form class=\"form-inline\" action=\"#\" method=\"get\">\r\n");
      out.write("\t\t\t\t<div class=\"easyui-panel\" style=\"width: 20%; max-width: 400px;\">\r\n");
      out.write("\t\t\t\t\t\t<select class=\"easyui-combobox\" name=\"state\"  style=\"width: 100%;\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"AL\">제목</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"AK\">내용</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"AZ\">재료명</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"AR\">닉네임</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"AR\">분류</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"AR\">소분류</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<input class=\"form-control mr-sm-2\" type=\"search\" placeholder=\"Search...\" aria-label=\"Search\" style=\"width: 55%\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-secondary\">\r\n");
      out.write("\t\t\t\t\t\t<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-search\" viewBox=\"0 0 16 16\">\r\n");
      out.write("\t\t\t\t\t\t  <path fill-rule=\"evenodd\"d=\"M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z\" />\r\n");
      out.write("\t\t\t\t\t\t  <path fill-rule=\"evenodd\"d=\"M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z\" />\r\n");
      out.write("\t\t\t\t\t\t</svg>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td style=\"width: 12%;  padding-top: 15px; text-align: right\">\r\n");
      out.write("\t\t\t\t<a href=\"/member/login.jsp\" style=\"font-family: Black Han Sans, sans-serif; color: black;\">\r\n");
      out.write("\t\t\t\t\t로그인\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td style=\"width: 13%; padding-top: 15px; padding-left:5px; text-align: left; \">\r\n");
      out.write("\t\t\t\t<a href=\"/member/joinMembership.jsp\" style=\"font-family: Black Han Sans, sans-serif; color: black;\">\r\n");
      out.write("\t\t\t\t\t회원가입\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</td>\r\n");
      out.write("\t\t\t");
} 
      out.write("</tr>\r\n");
      out.write("\t\t\t<!-- END Header -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- NavBar -->\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"2\" style=\"width: 100%;\">\r\n");
      out.write("\t\t\t\t");
      out.write("<table class=\"topnav\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<nav>\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav justify-content-center\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"nav-link\" href=\"/recommendation.jsp\">\r\n");
      out.write("\t\t\t\t\t\t\t\t추천 레시피\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\" >\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"nav-link\" href=\"/recipe/recipe.jsp\">\r\n");
      out.write("\t\t\t\t\t\t\t\t레시피\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\" >\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"nav-link\" href=\"/ranking.jsp\">\r\n");
      out.write("\t\t\t\t\t\t\t\t랭킹\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\" >\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"nav-link\"  href=\"/cookclass/cookingClassList.jsp\">\r\n");
      out.write("\t\t\t\t\t\t\t\t쿠킹 클래스\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\t<!-- END NavBar -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- Content -->\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td style=\"width: 19%; vertical-align: top;\">\r\n");
      out.write("\t\t\t\t<div class=\"btn-group-vertical\" style=\"width: 100%; margin-top: 12%\">\r\n");
      out.write("\t\t\t\t\t <button type=\"button\" class=\"btn btn-outline-dark\" style=\"text-align: left;\" onclick=\"reload()\">쿠킹 클래스 신청</button>\r\n");
      out.write("\t\t\t\t\t <button type=\"button\" class=\"btn btn-outline-dark\" style=\"text-align: left;\" onclick=\"location.href='/member/checkChef.np?m_id=");
      out.print(id);
      out.write("'\">쿠킹 클래스 등록</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td style=\"width: 70%; padding-top:3% ;padding-left: 5%; padding-right: 5%;\">\r\n");
      out.write("<table style=\"width: 100%\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td style=\"width: 80%; border: none;\">\r\n");
      out.write("\t\t\t\t<!-- Nav tabs -->\r\n");
      out.write("\t\t\t\t<ul class=\"nav nav-tabs\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link active\"\r\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"tab\" href=\"#home\">등록</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<div class=\"tab-content\">\r\n");
      out.write("\t\t\t\t\t<div id=\"home\" class=\"container tab-pane active\"  >\r\n");
      out.write("\t\t\t\t\t<form name=\"cookclassRegister\" action=\"/cookclass/createClass.np\" method=\"get\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" id=\"m_id\" name=\"m_id\" value=\"");
      out.print(session.getAttribute("id"));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>제목:</label>\r\n");
      out.write("\t\t\t\t\t\t\t <input type=\"text\"  value=\"어어엄청나게 맛있는 볶음밥\" class=\"form-control\" placeholder=\"어떤 요리인지 알 수 있도록 입력해 주세요. ex)누구나 쉽게 배울 수 있는 김치찜\"  id=\"c_cook\" name=\"c_cook\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>준비물:</label> \r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\"  value=\"밥,기름,파,베이컨,계란,다진마늘,후추,소금,설탕\" placeholder=\"요리에 필요한 준비물을 입력해주세요.\"  id=\"c_ingredients\" name=\"c_ingredients\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>실습주소:</label>\r\n");
      out.write("\t\t\t\t\t\t\t <input type=\"text\"  class=\"form-control\" value=\"인천광역시 부평구 선청동 240-1\" placeholder=\"실습주소를 입력해주세요.\" id=\"c_zip\" name=\"c_zip\">\r\n");
      out.write("\t\t\t\t\t\t\t <input class=\"btn btn-outline-dark\" type=\"button\" value=\"주소검색\" onClick=\"daumzip()\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>상세주소:</label>\r\n");
      out.write("\t\t\t\t\t\t\t <input type=\"text\" class=\"form-control\" value=\"oo아파트 00동 000호\" placeholder=\"상세주소를 입력해주세요.\" id=\"c_zipdetail\" name=\"c_zipdetail\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>날짜,시간:</label>\r\n");
      out.write("\t\t\t\t\t\t\t <input type=\"datetime-local\" class=\"form-control\"  value=\"2021-01-22 오후 03:17\" placeholder=\"실습날짜를 입력해주세요.\" id=\"c_date\" name=\"c_date\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>수강 최대 인원:</label>\r\n");
      out.write("\t\t\t\t\t\t\t <input type=\"text\" class=\"form-control\"  value=\"4\" placeholder=\"수강 최대 인원을 입력해주세요.\" id=\"c_member\" name=\"c_member\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<input class=\"btn btn-outline-dark\" type=\"button\" value=\"쿠킹클래스 등록\" onclick=\"check()\">\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t</td>\t\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<tr>\r\n");
      out.write("\t\t\t<td colspan=\"2\" style=\"width: 100%;\">\r\n");
      out.write("\t\t\t\t");
      out.write("<footer class=\"footer\">\r\n");
      out.write("  <div class=\"footer__addr\">\r\n");
      out.write("    <h2>Contact</h2>\r\n");
      out.write("    \r\n");
      out.write("      <a class=\"footer__btn\" href=\"mailto:example@gmail.com\">Email Us</a>\r\n");
      out.write("    </address>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  <ul class=\"footer__nav\">\r\n");
      out.write("    \r\n");
      out.write("    <li class=\"nav__item nav__item--extra\">\r\n");
      out.write("      <h2 class=\"nav__title\">Team members</h2>\r\n");
      out.write("      \r\n");
      out.write("      <ul class=\"nav__ul nav__ul--extra\">\r\n");
      out.write("        <li>\r\n");
      out.write("          <a href=\"#\">오성근</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        \r\n");
      out.write("        <li>\r\n");
      out.write("          <a href=\"#\">박한규</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        \r\n");
      out.write("        <li>\r\n");
      out.write("          <a href=\"#\">정주호</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        \r\n");
      out.write("        <li>\r\n");
      out.write("          <a href=\"#\">안준헌</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        \r\n");
      out.write("        <li>\r\n");
      out.write("          <a href=\"#\">이해민</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        \r\n");
      out.write("         <li>\r\n");
      out.write("          <a href=\"#\">양재화</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("          <a href=\"#\">최호연</a>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("    <li class=\"nav__item\">\r\n");
      out.write("      <h2 class=\"nav__title\">KOSMO</h2>\r\n");
      out.write("      \r\n");
      out.write("      <ul class=\"nav__ul\">\r\n");
      out.write("        <li>\r\n");
      out.write("          <a href=\"#\">Privacy Policy</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        \r\n");
      out.write("        <li>\r\n");
      out.write("          <a href=\"#\">Terms of Use</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        \r\n");
      out.write("        <li>\r\n");
      out.write("          <a href=\"#\">Sitemap</a>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </li>\r\n");
      out.write("  </ul>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"legal\">\r\n");
      out.write("    <p>&copy; 2021 Something. All rights reserved.</p>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"legal__links\">\r\n");
      out.write("      <span>Made with <span class=\"heart\">♥</span> NullPointer</span>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</footer>");
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\t<!-- End Footer -->\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
