/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2021-01-25 19:24:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.util.Map;
import java.util.List;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(11);
    _jspx_dependants.put("/navbar.jsp", Long.valueOf(1610644861660L));
    _jspx_dependants.put("/member/google2.jsp", Long.valueOf(1611179388331L));
    _jspx_dependants.put("/member/google1.jsp", Long.valueOf(1611321137736L));
    _jspx_dependants.put("/carousel2.jsp", Long.valueOf(1611322105178L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1609059653918L));
    _jspx_dependants.put("/loginOkHeader.jsp", Long.valueOf(1610894683264L));
    _jspx_dependants.put("/carousel.jsp", Long.valueOf(1610271764390L));
    _jspx_dependants.put("/content.jsp", Long.valueOf(1611321452107L));
    _jspx_dependants.put("/adminHeader.jsp", Long.valueOf(1610894989968L));
    _jspx_dependants.put("/common/bootstrap_common.jsp", Long.valueOf(1611325921671L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1610535124457L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Map");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>오늘 뭐 먹지?</title>\r\n");

       StringBuilder path = new StringBuilder(request.getContextPath());
       path.append("/");
    
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\" integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"image/favicon.ico\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(path.toString() );
      out.write("css/team.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(path.toString() );
      out.write("css/bootstrap.min.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path.toString() );
      out.write("js/bootstrap.min.js\"></script> \r\n");
      out.write("\r\n");
      out.write("<!-- carousel -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  \r\n");
      out.write("<!-- font -->\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Black+Han+Sans&display=swap\" rel=\"stylesheet\"> \r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Nanum+Pen+Script&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Sunflower:wght@300&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Single+Day&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Jua&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("<!-- EasyUI -->\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"https://www.jeasyui.com/easyui/themes/material/easyui.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"https://www.jeasyui.com/easyui/themes/icon.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"https://www.jeasyui.com/easyui/themes/color.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(path.toString() );
      out.write("css/demo.css\">\r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.print(path.toString() );
      out.write("js/commons.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://www.jeasyui.com/easyui/jquery.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://www.jeasyui.com/easyui/jquery.easyui.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("<!-- Ajax -->\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- kakao Login API -->\r\n");
      out.write("<script src=\"https://developers.kakao.com/sdk/js/kakao.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("<!-- google chart -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://www.gstatic.com/charts/loader.js\"></script>\r\n");
String indexNick =  (String)session.getAttribute("nick");
      out.write("<script>\r\n");
      out.write("//Get the button\r\n");
      out.write("var mybutton = document.getElementById(\"myBtn\");\r\n");
      out.write("\r\n");
      out.write("// When the user clicks on the button, scroll to the top of the document\r\n");
      out.write("function topFunction() {\r\n");
      out.write("  document.body.scrollTop = 0;\r\n");
      out.write("  document.documentElement.scrollTop = 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function logout() {\r\n");
      out.write("\t\tlocation.href=\"/member/logout.jsp\";\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("#myBtn {\r\n");
      out.write("  position: fixed;\r\n");
      out.write("  bottom: 45px;\r\n");
      out.write("  right: 45px;\r\n");
      out.write("  z-index: 99;\r\n");
      out.write("  font-size: 18px;\r\n");
      out.write("  border: 1px solid black;\r\n");
      out.write("  outline: none;\r\n");
      out.write("  background-color: white;\r\n");
      out.write("  color: black;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  padding: 15px;\r\n");
      out.write("  border-radius: 8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<table align=\"center\" style=\"width: 70% ; height: 100%;\">\r\n");
      out.write("\t\t\t<!-- Header -->\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t");
if(indexNick!=null && indexNick.equals("총관리자")){ 
      out.write("<td colspan=\"3\" style=\"width: 100%; padding-top: 2%; padding-bottom: 2%;\">\r\n");
      out.write("\t\t\t\t");
 String nick = (String)session.getAttribute("nick");
      out.write("<table style=\"width: 100%;\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td style=\"width: 25%; text-align: center;\">\r\n");
      out.write("\t\t\t\t<a href=\"/member/index.jsp\">\r\n");
      out.write("\t\t\t\t<input type=\"image\" src=\"/images/logo.jpg\"  style=\"width: 200px\">\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td style=\"width: 30%;  padding-top: 32px; text-align: right;\">\r\n");
      out.write("\t\t\t\t<p style=\"font-family: Black Han Sans, sans-serif; color: black;\">");
      out.print(nick);
      out.write("님 환영합니다</p>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td style=\"width: 8%;  padding-top: 15px; text-align: right\">\r\n");
      out.write("\t\t\t\t<a href=\"/adminControl.jsp\" style=\"font-family: Black Han Sans, sans-serif; color: black;\">\r\n");
      out.write("\t\t\t\t\t관리자페이지\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td style=\"width: 8%; padding-top: 15px; padding-left:5px; text-align: left; \">\r\n");
      out.write("\t\t\t\t<a href=\"javascript:logout();\" style=\"font-family: Black Han Sans, sans-serif; color: black;\">\r\n");
      out.write("\t\t\t\t\t로그아웃\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</td>\t\t\r\n");
      out.write("\t\t\t");
}else if(indexNick!=null && indexNick.length() >0 && ! indexNick.equals("총관리자")){ 
      out.write("<td colspan=\"3\" style=\"width: 100%; padding-top: 2%; padding-bottom: 2%;\">\r\n");
      out.write("\t\t\t\t");
 String nick = (String)session.getAttribute("nick");
      out.write("<table style=\"width: 100%;\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td style=\"width: 30%; text-align: center;\">\r\n");
      out.write("\t\t\t\t<a href=\"/member/index.jsp\">\r\n");
      out.write("\t\t\t\t\t<input type=\"image\" src=\"/images/logo.jpg\"  style=\"width: 200px\">\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td style=\"width: 45%; text-align: center;\">\r\n");
      out.write("\t\t\t\t<form class=\"form-inline\" action=\"#\" method=\"get\">\r\n");
      out.write("\t\t\t\t<div class=\"easyui-panel\" style=\"width: 20%; max-width: 400px;\">\r\n");
      out.write("\t\t\t\t\t\t<select class=\"easyui-combobox\" name=\"state\"  style=\"width: 100%;\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"AL\">제목</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"AK\">내용</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"AZ\">재료명</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"AR\">닉네임</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"AR\">분류</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"AR\">소분류</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<input class=\"form-control mr-sm-2\" type=\"search\" placeholder=\"Search...\" aria-label=\"Search\" style=\"width: 55%\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-secondary\">\r\n");
      out.write("\t\t\t\t\t\t\t<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-search\" viewBox=\"0 0 16 16\">\r\n");
      out.write("\t\t\t\t\t\t\t  <path fill-rule=\"evenodd\"d=\"M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z\" />\r\n");
      out.write("\t\t\t\t\t\t\t  <path fill-rule=\"evenodd\"d=\"M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z\" />\r\n");
      out.write("\t\t\t\t\t\t\t</svg>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td style=\"width: 12%;  padding-top: 32px; text-align: right;\">\r\n");
      out.write("\t\t\t\t<p style=\"font-family: Black Han Sans, sans-serif; color: black;\">");
      out.print(nick);
      out.write("님 환영합니다</p>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td style=\"width: 8%;  padding-top: 15px; text-align: right\">\r\n");
      out.write("\t\t\t\t<a href=\"/member/mypage.jsp\" style=\"font-family: Black Han Sans, sans-serif; color: black;\">\r\n");
      out.write("\t\t\t\t\t마이페이지\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td style=\"width: 8%; padding-top: 15px; padding-left:5px; text-align: left; \">\r\n");
      out.write("\t\t\t\t<a href=\"javascript:logout();\"  style=\"font-family: Black Han Sans, sans-serif; color: black; cursor: pointer;\">\r\n");
      out.write("\t\t\t\t\t로그아웃\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</td>\r\n");
      out.write("\t\t\t");
}else{ 
      out.write("<td colspan=\"3\" style=\"width: 100%; padding-top: 2%; padding-bottom: 2%;\">\r\n");
      out.write("\t\t\t\t");
      out.write("<table style=\"width: 100%;\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td style=\"width: 30%; text-align: center;\">\r\n");
      out.write("\t\t\t\t<a href=\"/member/index.jsp\">\r\n");
      out.write("\t\t\t\t\t<input type=\"image\" src=\"/images/logo.jpg\"  style=\"width: 200px\">\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td style=\"width: 45%; text-align: center;\">\r\n");
      out.write("\t\t\t\t<form class=\"form-inline\" action=\"#\" method=\"get\">\r\n");
      out.write("\t\t\t\t<div class=\"easyui-panel\" style=\"width: 20%; max-width: 400px;\">\r\n");
      out.write("\t\t\t\t\t\t<select class=\"easyui-combobox\" name=\"state\"  style=\"width: 100%;\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"AL\">제목</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"AK\">내용</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"AZ\">재료명</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"AR\">닉네임</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"AR\">분류</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"AR\">소분류</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<input class=\"form-control mr-sm-2\" type=\"search\" placeholder=\"Search...\" aria-label=\"Search\" style=\"width: 55%\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-secondary\">\r\n");
      out.write("\t\t\t\t\t\t<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-search\" viewBox=\"0 0 16 16\">\r\n");
      out.write("\t\t\t\t\t\t  <path fill-rule=\"evenodd\"d=\"M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z\" />\r\n");
      out.write("\t\t\t\t\t\t  <path fill-rule=\"evenodd\"d=\"M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z\" />\r\n");
      out.write("\t\t\t\t\t\t</svg>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td style=\"width: 12%;  padding-top: 15px; text-align: right\">\r\n");
      out.write("\t\t\t\t<a href=\"/member/login.jsp\" style=\"font-family: Black Han Sans, sans-serif; color: black;\">\r\n");
      out.write("\t\t\t\t\t로그인\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td style=\"width: 13%; padding-top: 15px; padding-left:5px; text-align: left; \">\r\n");
      out.write("\t\t\t\t<a href=\"/member/joinMembership.jsp\" style=\"font-family: Black Han Sans, sans-serif; color: black;\">\r\n");
      out.write("\t\t\t\t\t회원가입\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</td>\r\n");
      out.write("\t\t\t");
} 
      out.write("</tr>\r\n");
      out.write("\t\t\t<!-- END Header -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- NavBar -->\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"3\" style=\"width: 100%;\">\r\n");
      out.write("\t\t\t\t");
      out.write("<table class=\"topnav\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<nav>\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav justify-content-center\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"nav-link\" href=\"/recommendation.jsp\">\r\n");
      out.write("\t\t\t\t\t\t\t\t추천 레시피\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\" >\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"nav-link\" href=\"/recipe/recipe.jsp\">\r\n");
      out.write("\t\t\t\t\t\t\t\t레시피\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\" >\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"nav-link\" href=\"/ranking.jsp\">\r\n");
      out.write("\t\t\t\t\t\t\t\t랭킹\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\" >\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"nav-link\"  href=\"/cookclass/cookingClassList.jsp\">\r\n");
      out.write("\t\t\t\t\t\t\t\t쿠킹 클래스\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\t<!-- END NavBar -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- Carousel -->\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"3\" style=\"width: 100%; padding-top: 2%; padding-bottom: 2%;\">\r\n");
      out.write("\t\t\t\t");
      out.write("<table>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td  style=\"width: 100%;\">\r\n");
      out.write("\t\t\t<div id=\"demo\" class=\"carousel slide\" data-ride=\"carousel\"  style=\"width: 100%;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Indicators -->\r\n");
      out.write("\t\t\t\t<ul class=\"carousel-indicators\">\r\n");
      out.write("\t\t\t\t\t<li data-target=\"#demo\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("\t\t\t\t\t<li data-target=\"#demo\" data-slide-to=\"1\"></li>\r\n");
      out.write("\t\t\t\t\t<li data-target=\"#demo\" data-slide-to=\"2\"></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!--The slideshow -->\r\n");
      out.write("\t\t\t\t<div class=\"carousel-inner\" >\r\n");
      out.write("\t\t\t\t\t<div class=\"carousel-item active\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"/images/index1.jpg\" style=\"width: 100%; height: 100%\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"carousel-item\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"/images/index2.jpg\" style=\"width: 100%; height: 100%;\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"carousel-item\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"/images/index3.jpg\" style=\"width: 100%; height: 100%;\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Left and right controls -->\r\n");
      out.write("\t\t\t\t<a class=\"carousel-control-prev\" href=\"#demo\" data-slide=\"prev\">\r\n");
      out.write("\t\t\t\t\t<span class=\"carousel-control-prev-icon\"></span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t <a class=\"carousel-control-next\" href=\"#demo\" data-slide=\"next\">\r\n");
      out.write("\t\t\t\t\t<span class=\"carousel-control-next-icon\"></span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\t<!-- End Carousel -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- Content -->\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td style=\"width: 55%\">\r\n");
      out.write("\t\t\t\t");

	int tot = 0;
	List<Map<String,Object>> boardList = null;
	boardList = (List<Map<String,Object>>)request.getAttribute("boardList");
	if(boardList !=null){
		tot = boardList.size();
	}
	

      out.write("<div class=\"container\" style=\"background-color: white;\">\r\n");
      out.write("\t<table style=\"width: 100%\">\r\n");
      out.write("  \t\t<tr>\r\n");
      out.write("  \t\t\t<td>\r\n");
      out.write("  \t\t\t\t<h1 style=\"font-family: 'Nanum Pen Script', cursive; padding-left: 10px;\">신규 레시피</h1>\r\n");
      out.write("  \t\t\t</td>\r\n");
      out.write("  \t\t\t<td style=\"text-align: right; padding-top: 20px;\">\r\n");
      out.write("  \t\t\t\t<a href=\"#\" style=\"font-family: 'Nanum Pen Script', cursive; font-size: 20px; color: black;\">더보기</a>\r\n");
      out.write("  \t\t\t</td>\r\n");
      out.write("  \t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("  <table class=\"table table-hover\">\r\n");
      out.write("    <tbody>\r\n");

			for(int i=0;i<4;i++){
			//Map<String,Object> rmap = boardList.get(i);

      out.write("<tr style=\"cursor: pointer;\">\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write(" \t\t\t     url : \"/recipe/recipeList.np\"\r\n");
      out.write(" \t\t         ,success : function (result) { \r\n");
      out.write(" \t\t        \t $.each(result, function (index, item) {\r\n");
      out.write(" \t\t        \t       //table에 출력   \r\n");
      out.write(" \t\t        \t      if(item.C_COOK != null){\r\n");
      out.write(" \t\t\t        \t      var str = '<table style=\"width:100%; margin-bottom:5%\"><tr><td style=\"width:50%\"> 제목 : '+item.C_COOK+'</td>';\r\n");
      out.write(" \t\t\t        \t      str += '<td style=\"float: right;\">작성자 : '+item.C_COOK+'</td></tr></table>'; \r\n");
      out.write(" \t\t\t        \t      $('#newRecipe').append(str);\r\n");
      out.write(" \t\t        \t      }\r\n");
      out.write(" \t\t        \t   });\r\n");
      out.write(" \t\t        \t}\r\n");
      out.write(" \t\t         });\r\n");
      out.write(" \t\t</script>\r\n");
      out.write(" \t\t</td>\r\n");
      out.write("\t</tr>\r\n");

			}

      out.write("</tbody>\r\n");
      out.write("  </table>\r\n");
      out.write("</div>");
      out.write("</td>\r\n");
      out.write("\t\t\t<td style=\"width: 45%; padding-left:4% \">\r\n");
      out.write("\t\t\t\t<h1 style=\"font-family: 'Nanum Pen Script', cursive; padding-left: px;\">좋아요 분포도</h1>\r\n");
      out.write("\t\t\t\t<table class=\"table\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    google.charts.load('current', {packages: ['corechart']});\r\n");
      out.write("    google.charts.setOnLoadCallback(drawChart);\r\n");
      out.write("    function drawChart() {\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            url: '/recipe/forChart.np?field=LARGE',\r\n");
      out.write("            dataType: 'JSON',\r\n");
      out.write("            success: function (jsonData) {\r\n");
      out.write("                var data = new google.visualization.DataTable();\r\n");
      out.write("                data.addColumn('string', '대분류');\r\n");
      out.write("                data.addColumn('number', '좋아요');\r\n");
      out.write("                for (var i = 0; i < jsonData.length; i++) {\r\n");
      out.write("                    data.addRow([jsonData[i].대분류, jsonData[i].좋아요]);\r\n");
      out.write("                }\r\n");
      out.write("                var options = {\r\n");
      out.write("                        'title':'대분류별 좋아요 분포',\r\n");
      out.write("                        'width':400,\r\n");
      out.write("                        'height':400,\r\n");
      out.write("                        legend:'none',\r\n");
      out.write("                        pieHole: 0.3\r\n");
      out.write("                };\r\n");
      out.write("                var chart = new google.visualization.PieChart(document.getElementById('myChart1'));\r\n");
      out.write("                chart.draw(data, options);\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("    google.setOnLoadCallback(drawChart);\r\n");
      out.write("</script>\r\n");
      out.write("<div id=\"myChart1\" style=\"\"></div>\r\n");
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    google.charts.load('current', {packages: ['corechart']});\r\n");
      out.write("    google.charts.setOnLoadCallback(drawChart);\r\n");
      out.write("    function drawChart() {\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            url: '/recipe/forChart.np?field=SMALL',\r\n");
      out.write("            dataType: 'JSON',\r\n");
      out.write("            success: function (jsonData) {\r\n");
      out.write("                var data = new google.visualization.DataTable();\r\n");
      out.write("                data.addColumn('string', '소분류');\r\n");
      out.write("                data.addColumn('number', '좋아요');\r\n");
      out.write("                for (var i = 0; i < jsonData.length; i++) {\r\n");
      out.write("                    data.addRow([jsonData[i].소분류, jsonData[i].좋아요]);\r\n");
      out.write("                }\r\n");
      out.write("                var options = {\r\n");
      out.write("                        'title':'소분류별 좋아요 분포',\r\n");
      out.write("                        'width':400,\r\n");
      out.write("                        'height':400,\r\n");
      out.write("                        pieSliceText:'label',\r\n");
      out.write("                        is3D:true,\r\n");
      out.write("                        slices:{\r\n");
      out.write("                           0:{offset:0.2}\r\n");
      out.write("                           ,5:{offset:0.5}\r\n");
      out.write("                        }\r\n");
      out.write("                };\r\n");
      out.write("                var chart = new google.visualization.PieChart(document.getElementById('myChart2'));\r\n");
      out.write("                chart.draw(data, options);\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("    google.setOnLoadCallback(drawChart);\r\n");
      out.write("</script>\r\n");
      out.write("<div id=\"myChart2\" style=\"\"></div>\r\n");
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\t<!-- End Content -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!--  Carousel 2 -->\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"3\" style=\"width: 100%;\">\r\n");
      out.write("\t\t\t\t");
      out.write("<table style=\"width: 100%\">\r\n");
      out.write("  \t\t<tr>\r\n");
      out.write("  \t\t\t<td>\r\n");
      out.write("  \t\t\t\t <h1 style=\"font-family: 'Nanum Pen Script', cursive; padding-left: 10px;\">인기 셰프</h1>\r\n");
      out.write("  \t\t\t</td>\r\n");
      out.write("  \t\t\t<td style=\"text-align: right; padding-top: 20px;\">\r\n");
      out.write("  \t\t\t\t<a href=\"/ranking.jsp?ranking=0\" style=\"font-family: 'Nanum Pen Script', cursive; font-size: 20px; color: black;\">더보기</a>\r\n");
      out.write("  \t\t\t</td>\r\n");
      out.write("  \t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("<table align=\"center\" style=\"width: 100%; \" class=\"table\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td style=\"width: 100%;\">\r\n");
      out.write("\t\t\t<div id=\"demo2\" class=\"carousel slide\" data-ride=\"carousel\"   style=\"width: 100%;\">\r\n");
      out.write("\t\t\t\t<!-- Indicators -->\r\n");
      out.write("\t\t\t\t<ul class=\"carousel-indicators\">\r\n");
      out.write("\t\t\t\t\t<li data-target=\"#demo2\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("\t\t\t\t\t<li data-target=\"#demo2\" data-slide-to=\"1\"></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!--The slideshow -->\r\n");
      out.write("\t\t\t\t<div class=\"carousel-inner\" style=\"height: 300px;\">\r\n");
      out.write("\t\t\t\t\t<div class=\"carousel-item active\">\r\n");
      out.write("\t\t\t\t\t\t<div style=\"margin-left: 140px;\">\r\n");
      out.write("\t\t\t\t\t\t");

							for(int i=0;i<5;i++){
							//Map<String,Object> rmap = boardList.get(i);
						
      out.write("<div style=\"float: left;\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"/images/chef.png\" style=\"width:150px; border-radius: 50%; border: solid 1px black; margin: 30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2 style=\"font-family: 'Nanum Pen Script', cursive; padding-left: 10px; text-align: center\">*** 셰프님</h2>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t");

								}
						
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"carousel-item\">\r\n");
      out.write("\t\t\t\t\t\t<div style=\"margin-left: 140px;\">\r\n");
      out.write("\t\t\t\t\t\t");

							for(int i=0;i<5;i++){
							//Map<String,Object> rmap = boardList.get(i);
						
      out.write("<div style=\"float: left;\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"/images/chef2.png\" style=\"width:150px; border-radius: 50%; border: solid 1px black; margin: 30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2 style=\"font-family: 'Nanum Pen Script', cursive; padding-left: 10px; text-align: center\">*** 셰프님</h2>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t");

								}
						
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Left and right controls -->\r\n");
      out.write("\t\t\t\t<a class=\"carousel-control-prev\" href=\"#demo2\" data-slide=\"prev\">\r\n");
      out.write("\t\t\t\t\t<span class=\"carousel-control-prev-icon\" style=\"padding-bottom: 10px;\"></span>\r\n");
      out.write("\t\t\t\t</a> <a class=\"carousel-control-next\" href=\"#demo2\" data-slide=\"next\">\r\n");
      out.write("\t\t\t\t\t<span class=\"carousel-control-next-icon\"></span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>");
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\t<!-- End Carousel 2 -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- Footer -->\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"3\" style=\"padding-top: 8%\">\r\n");
      out.write("\t\t\t\t");
      out.write("<footer class=\"footer\">\r\n");
      out.write("  <div class=\"footer__addr\">\r\n");
      out.write("    <h2>Contact</h2>\r\n");
      out.write("    \r\n");
      out.write("      <a class=\"footer__btn\" href=\"mailto:example@gmail.com\">Email Us</a>\r\n");
      out.write("    </address>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  <ul class=\"footer__nav\">\r\n");
      out.write("    \r\n");
      out.write("    <li class=\"nav__item nav__item--extra\">\r\n");
      out.write("      <h2 class=\"nav__title\">Team members</h2>\r\n");
      out.write("      \r\n");
      out.write("      <ul class=\"nav__ul nav__ul--extra\">\r\n");
      out.write("        <li>\r\n");
      out.write("          <a href=\"#\">오성근</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        \r\n");
      out.write("        <li>\r\n");
      out.write("          <a href=\"#\">박한규</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        \r\n");
      out.write("        <li>\r\n");
      out.write("          <a href=\"#\">정주호</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        \r\n");
      out.write("        <li>\r\n");
      out.write("          <a href=\"#\">안준헌</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        \r\n");
      out.write("        <li>\r\n");
      out.write("          <a href=\"#\">이해민</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        \r\n");
      out.write("         <li>\r\n");
      out.write("          <a href=\"#\">양재화</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("          <a href=\"#\">최호연</a>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("    <li class=\"nav__item\">\r\n");
      out.write("      <h2 class=\"nav__title\">KOSMO</h2>\r\n");
      out.write("      \r\n");
      out.write("      <ul class=\"nav__ul\">\r\n");
      out.write("        <li>\r\n");
      out.write("          <a href=\"#\">Privacy Policy</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        \r\n");
      out.write("        <li>\r\n");
      out.write("          <a href=\"#\">Terms of Use</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        \r\n");
      out.write("        <li>\r\n");
      out.write("          <a href=\"#\">Sitemap</a>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </li>\r\n");
      out.write("  </ul>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"legal\">\r\n");
      out.write("    <p>&copy; 2021 Something. All rights reserved.</p>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"legal__links\">\r\n");
      out.write("      <span>Made with <span class=\"heart\">♥</span> NullPointer</span>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</footer>");
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\t<!-- End Footer -->\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<button onclick=\"topFunction()\" id=\"myBtn\" title=\"Go to top\">Top</button>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
